'use strict';
// Paymint - single-file build (backend + embedded dashboard). Zero dependencies.
// Run: node --experimental-sqlite index.js
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');

const EMBEDDED_HTML = Buffer.from('PCFkb2N0eXBlIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CjxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgo8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEsIHZpZXdwb3J0LWZpdD1jb3ZlciIgLz4KPHRpdGxlPlBheW1pbnQg4oCUIERhc2hib2FyZDwvdGl0bGU+CjxzdHlsZT4KICA6cm9vdHsKICAgIC0tYmc6IzBiMTIyMDsgLS1iZzI6IzBlMTcyNjsgLS1jYXJkOiMxNDFmMzM7IC0tY2FyZDI6IzFhMjc0MDsgLS1saW5lOiMyNjMzNDk7CiAgICAtLXRleHQ6I2VhZjFmYjsgLS1tdXRlZDojOTNhNGJmOyAtLWJyYW5kOiMxMmQ2YTA7IC0tYnJhbmQyOiMwZmI0ODg7IC0tYnJhbmRmYWRlOnJnYmEoMTgsMjE0LDE2MCwuMTQpOwogICAgLS1ibHVlOiM0ZjhjZmY7IC0tYW1iZXI6I2Y2YjU0NTsgLS1yZWQ6I2ZmNWQ2YzsgLS12aW9sZXQ6IzlhN2JmZjsKICAgIC0tcmFkaXVzOjE2cHg7IC0tc2hhZG93OjAgOHB4IDI4cHggcmdiYSgwLDAsMCwuMjgpOwogIH0KICBAbWVkaWEgKHByZWZlcnMtY29sb3Itc2NoZW1lOiBsaWdodCl7CiAgICA6cm9vdHsgLS1iZzojZWVmMmY4OyAtLWJnMjojZTdlZGY2OyAtLWNhcmQ6I2ZmZmZmZjsgLS1jYXJkMjojZjRmN2ZjOyAtLWxpbmU6I2UzZTlmMjsKICAgICAgLS10ZXh0OiMxMDIxM2I7IC0tbXV0ZWQ6IzVmNmY4YTsgLS1icmFuZGZhZGU6cmdiYSgxOCwyMTQsMTYwLC4xMik7IC0tc2hhZG93OjAgOHB4IDI0cHggcmdiYSgyMCw0MCw4MCwuMDgpOyB9CiAgfQogICp7Ym94LXNpemluZzpib3JkZXItYm94fQogIGh0bWwsYm9keXttYXJnaW46MH0KICBib2R5e2ZvbnQ6MTVweC8xLjU1IHN5c3RlbS11aSwtYXBwbGUtc3lzdGVtLCJTZWdvZSBVSSIsUm9ib3RvLHNhbnMtc2VyaWY7YmFja2dyb3VuZDoKICAgIHJhZGlhbC1ncmFkaWVudCgxMjAwcHggNTAwcHggYXQgMTAwJSAtMTAlLCB2YXIoLS1icmFuZGZhZGUpLCB0cmFuc3BhcmVudCA2MCUpLAogICAgdmFyKC0tYmcpO2NvbG9yOnZhcigtLXRleHQpO21pbi1oZWlnaHQ6MTAwdmh9CiAgYnV0dG9ue2ZvbnQ6aW5oZXJpdDtjdXJzb3I6cG9pbnRlcjtib3JkZXI6bm9uZTtib3JkZXItcmFkaXVzOjEycHg7cGFkZGluZzoxMHB4IDE2cHg7YmFja2dyb3VuZDp2YXIoLS1icmFuZCk7Y29sb3I6IzA0MjMxYjtmb250LXdlaWdodDo3MDA7dHJhbnNpdGlvbjp0cmFuc2Zvcm0gLjA2cyBlYXNlLGZpbHRlciAuMTVzfQogIGJ1dHRvbjphY3RpdmV7dHJhbnNmb3JtOnNjYWxlKC45Nyl9IGJ1dHRvbjpob3ZlcntmaWx0ZXI6YnJpZ2h0bmVzcygxLjA1KX0KICBidXR0b24uZ2hvc3R7YmFja2dyb3VuZDp0cmFuc3BhcmVudDtjb2xvcjp2YXIoLS10ZXh0KTtib3JkZXI6MXB4IHNvbGlkIHZhcigtLWxpbmUpO2ZvbnQtd2VpZ2h0OjYwMH0KICBidXR0b24ub2t7YmFja2dyb3VuZDp2YXIoLS1icmFuZCk7Y29sb3I6IzA0MjMxYn0gYnV0dG9uLmJhZHtiYWNrZ3JvdW5kOnZhcigtLXJlZCk7Y29sb3I6I2ZmZn0gYnV0dG9uLndhcm57YmFja2dyb3VuZDp2YXIoLS1hbWJlcik7Y29sb3I6IzJhMWMwMH0KICBidXR0b24uc217cGFkZGluZzo3cHggMTJweDtmb250LXNpemU6MTNweDtib3JkZXItcmFkaXVzOjEwcHh9CiAgYnV0dG9uOmRpc2FibGVke29wYWNpdHk6LjU7Y3Vyc29yOm5vdC1hbGxvd2VkfQogIGlucHV0LHNlbGVjdHtmb250OmluaGVyaXQ7d2lkdGg6MTAwJTtwYWRkaW5nOjEycHggMTRweDtib3JkZXItcmFkaXVzOjEycHg7Ym9yZGVyOjFweCBzb2xpZCB2YXIoLS1saW5lKTtiYWNrZ3JvdW5kOnZhcigtLWJnMik7Y29sb3I6dmFyKC0tdGV4dCk7b3V0bGluZTpub25lO3RyYW5zaXRpb246Ym9yZGVyLWNvbG9yIC4xNXN9CiAgaW5wdXQ6Zm9jdXN7Ym9yZGVyLWNvbG9yOnZhcigtLWJyYW5kKX0KICBsYWJlbHtkaXNwbGF5OmJsb2NrO2ZvbnQtc2l6ZToxMi41cHg7Zm9udC13ZWlnaHQ6NjAwO2NvbG9yOnZhcigtLW11dGVkKTttYXJnaW46MTJweCAwIDVweDtsZXR0ZXItc3BhY2luZzouMnB4fQogIC53cmFwe21heC13aWR0aDoxMDUwcHg7bWFyZ2luOjAgYXV0bztwYWRkaW5nOjE2cHh9CiAgLyogaGVhZGVyICovCiAgaGVhZGVye2Rpc3BsYXk6ZmxleDthbGlnbi1pdGVtczpjZW50ZXI7Z2FwOjEycHg7cGFkZGluZzoxNHB4IDE4cHg7YmFja2dyb3VuZDpsaW5lYXItZ3JhZGllbnQoOTBkZWcsdmFyKC0tY2FyZCksdmFyKC0tY2FyZDIpKTsKICAgIGJvcmRlci1ib3R0b206MXB4IHNvbGlkIHZhcigtLWxpbmUpO3Bvc2l0aW9uOnN0aWNreTt0b3A6MDt6LWluZGV4OjU7YmFja2Ryb3AtZmlsdGVyOmJsdXIoOHB4KX0KICAuYnJhbmR7ZGlzcGxheTpmbGV4O2FsaWduLWl0ZW1zOmNlbnRlcjtnYXA6OXB4O2ZvbnQtd2VpZ2h0OjgwMDtmb250LXNpemU6MTlweDtsZXR0ZXItc3BhY2luZzotLjNweH0KICAuYnJhbmQgLm1hcmt7d2lkdGg6MzBweDtoZWlnaHQ6MzBweDtib3JkZXItcmFkaXVzOjlweDtiYWNrZ3JvdW5kOmxpbmVhci1ncmFkaWVudCgxMzVkZWcsdmFyKC0tYnJhbmQpLHZhcigtLWJsdWUpKTtkaXNwbGF5OmdyaWQ7cGxhY2UtaXRlbXM6Y2VudGVyO2NvbG9yOiMwNDIzMWI7Ym94LXNoYWRvdzowIDRweCAxMnB4IHZhcigtLWJyYW5kZmFkZSl9CiAgLnNwYWNlcntmbGV4OjF9CiAgLndob3tjb2xvcjp2YXIoLS1tdXRlZCk7Zm9udC1zaXplOjEyLjVweDt0ZXh0LWFsaWduOnJpZ2h0O2xpbmUtaGVpZ2h0OjEuM30KICAud2hvIGJ7Y29sb3I6dmFyKC0tdGV4dCk7Zm9udC13ZWlnaHQ6NzAwO2Rpc3BsYXk6YmxvY2t9CiAgLyogdGFicyAqLwogIC50YWJze2Rpc3BsYXk6ZmxleDtnYXA6OHB4O2ZsZXgtd3JhcDp3cmFwO21hcmdpbjoxNnB4IDB9CiAgLnRhYnMgYnV0dG9ue2JhY2tncm91bmQ6dmFyKC0tY2FyZCk7Y29sb3I6dmFyKC0tbXV0ZWQpO2JvcmRlcjoxcHggc29saWQgdmFyKC0tbGluZSk7Zm9udC13ZWlnaHQ6NjAwfQogIC50YWJzIGJ1dHRvbi5hY3RpdmV7YmFja2dyb3VuZDp2YXIoLS1icmFuZCk7Y29sb3I6IzA0MjMxYjtib3JkZXItY29sb3I6dHJhbnNwYXJlbnQ7Ym94LXNoYWRvdzowIDZweCAxNnB4IHZhcigtLWJyYW5kZmFkZSl9CiAgLyogY2FyZHMgKi8KICAuY2FyZHtiYWNrZ3JvdW5kOnZhcigtLWNhcmQpO2JvcmRlcjoxcHggc29saWQgdmFyKC0tbGluZSk7Ym9yZGVyLXJhZGl1czp2YXIoLS1yYWRpdXMpO3BhZGRpbmc6MTZweDttYXJnaW4tYm90dG9tOjE0cHg7Ym94LXNoYWRvdzp2YXIoLS1zaGFkb3cpfQogIC5ncmlke2Rpc3BsYXk6Z3JpZDtnYXA6MTJweDtncmlkLXRlbXBsYXRlLWNvbHVtbnM6cmVwZWF0KGF1dG8tZmlsbCxtaW5tYXgoMTUwcHgsMWZyKSl9CiAgLnJvd3tkaXNwbGF5OmZsZXg7Z2FwOjEwcHg7YWxpZ24taXRlbXM6Y2VudGVyO2ZsZXgtd3JhcDp3cmFwfQogIC5iZXR3ZWVue2Rpc3BsYXk6ZmxleDthbGlnbi1pdGVtczpjZW50ZXI7anVzdGlmeS1jb250ZW50OnNwYWNlLWJldHdlZW47Z2FwOjEwcHh9CiAgLnBpbGx7Zm9udC1zaXplOjExLjVweDtwYWRkaW5nOjNweCAxMHB4O2JvcmRlci1yYWRpdXM6OTk5cHg7Zm9udC13ZWlnaHQ6NzAwO2xldHRlci1zcGFjaW5nOi4ycHh9CiAgLnBpbGwucGVuZGluZ3tiYWNrZ3JvdW5kOnJnYmEoMjQ2LDE4MSw2OSwuMTYpO2NvbG9yOnZhcigtLWFtYmVyKX0KICAucGlsbC5hY3RpdmV7YmFja2dyb3VuZDp2YXIoLS1icmFuZGZhZGUpO2NvbG9yOnZhcigtLWJyYW5kKX0KICAucGlsbC5zdXNwZW5kZWQsLnBpbGwucmVqZWN0ZWQsLnBpbGwub3ZlcmR1ZXtiYWNrZ3JvdW5kOnJnYmEoMjU1LDkzLDEwOCwuMTYpO2NvbG9yOnZhcigtLXJlZCl9CiAgLnBpbGwuY29tcGxldGVke2JhY2tncm91bmQ6cmdiYSg3OSwxNDAsMjU1LC4xNik7Y29sb3I6dmFyKC0tYmx1ZSl9CiAgLnBpbGwubG9ja2Vke2JhY2tncm91bmQ6cmdiYSgyNTUsOTMsMTA4LC4xOCk7Y29sb3I6dmFyKC0tcmVkKX0KICAucGlsbC5wYWlke2JhY2tncm91bmQ6dmFyKC0tYnJhbmRmYWRlKTtjb2xvcjp2YXIoLS1icmFuZCl9CiAgLm11dGVke2NvbG9yOnZhcigtLW11dGVkKX0gLnNtYWxse2ZvbnQtc2l6ZToxM3B4fQogIC8qIGtwaSAqLwogIC5rcGktY2FyZHtiYWNrZ3JvdW5kOnZhcigtLWNhcmQpO2JvcmRlcjoxcHggc29saWQgdmFyKC0tbGluZSk7Ym9yZGVyLXJhZGl1czp2YXIoLS1yYWRpdXMpO3BhZGRpbmc6MTVweDtib3gtc2hhZG93OnZhcigtLXNoYWRvdyk7cG9zaXRpb246cmVsYXRpdmU7b3ZlcmZsb3c6aGlkZGVufQogIC5rcGktY2FyZCAuaWN7d2lkdGg6MzRweDtoZWlnaHQ6MzRweDtib3JkZXItcmFkaXVzOjEwcHg7ZGlzcGxheTpncmlkO3BsYWNlLWl0ZW1zOmNlbnRlcjtmb250LXNpemU6MTdweDttYXJnaW4tYm90dG9tOjEwcHh9CiAgLmtwaS1jYXJkIC5sYmx7Y29sb3I6dmFyKC0tbXV0ZWQpO2ZvbnQtc2l6ZToxMi41cHg7Zm9udC13ZWlnaHQ6NjAwfQogIC5rcGktY2FyZCAudmFse2ZvbnQtc2l6ZToyM3B4O2ZvbnQtd2VpZ2h0OjgwMDtsZXR0ZXItc3BhY2luZzotLjVweDttYXJnaW4tdG9wOjJweH0KICAvKiBwcm9ncmVzcyAqLwogIC5iYXJ7aGVpZ2h0OjhweDtib3JkZXItcmFkaXVzOjk5OXB4O2JhY2tncm91bmQ6dmFyKC0tYmcyKTtvdmVyZmxvdzpoaWRkZW47bWFyZ2luOjlweCAwIDRweH0KICAuYmFyPml7ZGlzcGxheTpibG9jaztoZWlnaHQ6MTAwJTtib3JkZXItcmFkaXVzOjk5OXB4O2JhY2tncm91bmQ6bGluZWFyLWdyYWRpZW50KDkwZGVnLHZhcigtLWJyYW5kKSx2YXIoLS1icmFuZDIpKTt0cmFuc2l0aW9uOndpZHRoIC40cyBlYXNlfQogIHRhYmxle3dpZHRoOjEwMCU7Ym9yZGVyLWNvbGxhcHNlOmNvbGxhcHNlfQogIHRoLHRke3RleHQtYWxpZ246bGVmdDtwYWRkaW5nOjlweCA2cHg7Ym9yZGVyLWJvdHRvbToxcHggc29saWQgdmFyKC0tbGluZSk7Zm9udC1zaXplOjE0cHh9CiAgdGh7Y29sb3I6dmFyKC0tbXV0ZWQpO2ZvbnQtd2VpZ2h0OjYwMDtmb250LXNpemU6MTIuNXB4fQogIC50aHVtYnN7ZGlzcGxheTpmbGV4O2dhcDo4cHh9IC50aHVtYnMgaW1ne3dpZHRoOjcwcHg7aGVpZ2h0OjcwcHg7b2JqZWN0LWZpdDpjb3Zlcjtib3JkZXItcmFkaXVzOjEwcHg7Ym9yZGVyOjFweCBzb2xpZCB2YXIoLS1saW5lKTtjdXJzb3I6cG9pbnRlcn0KICAuY2VudGVye21pbi1oZWlnaHQ6ODR2aDtkaXNwbGF5OmZsZXg7YWxpZ24taXRlbXM6Y2VudGVyO2p1c3RpZnktY29udGVudDpjZW50ZXI7cGFkZGluZzoyMHB4fQogIC5hdXRoe3dpZHRoOjM4MHB4O21heC13aWR0aDo5NHZ3fQogIC50b2FzdHtwb3NpdGlvbjpmaXhlZDtsZWZ0OjUwJTtib3R0b206MjRweDt0cmFuc2Zvcm06dHJhbnNsYXRlWCgtNTAlKTtiYWNrZ3JvdW5kOnZhcigtLWNhcmQyKTtib3JkZXI6MXB4IHNvbGlkIHZhcigtLWxpbmUpO3BhZGRpbmc6MTJweCAxOHB4O2JvcmRlci1yYWRpdXM6MTJweDt6LWluZGV4OjMwO21heC13aWR0aDo5MHZ3O2JveC1zaGFkb3c6dmFyKC0tc2hhZG93KTtmb250LXdlaWdodDo2MDA7Zm9udC1zaXplOjE0cHh9CiAgLnRvYXN0LmJhZHtib3JkZXItY29sb3I6dmFyKC0tcmVkKX0gLnRvYXN0Lm9re2JvcmRlci1jb2xvcjp2YXIoLS1icmFuZCl9CiAgZGlhbG9ne2JvcmRlcjpub25lO2JvcmRlci1yYWRpdXM6dmFyKC0tcmFkaXVzKTtiYWNrZ3JvdW5kOnZhcigtLWNhcmQpO2NvbG9yOnZhcigtLXRleHQpO21heC13aWR0aDo1NDBweDt3aWR0aDo5NHZ3O3BhZGRpbmc6MDtib3gtc2hhZG93OjAgMjBweCA2MHB4IHJnYmEoMCwwLDAsLjQpfQogIGRpYWxvZzo6YmFja2Ryb3B7YmFja2dyb3VuZDpyZ2JhKDUsMTAsMjAsLjYpO2JhY2tkcm9wLWZpbHRlcjpibHVyKDNweCl9CiAgLmRsZy1oe3BhZGRpbmc6MTVweCAxOHB4O2JvcmRlci1ib3R0b206MXB4IHNvbGlkIHZhcigtLWxpbmUpO2ZvbnQtd2VpZ2h0OjgwMH0KICAuZGxnLWJ7cGFkZGluZzoxOHB4O21heC1oZWlnaHQ6NzB2aDtvdmVyZmxvdzphdXRvfSAuZGxnLWZ7cGFkZGluZzoxM3B4IDE4cHg7Ym9yZGVyLXRvcDoxcHggc29saWQgdmFyKC0tbGluZSk7ZGlzcGxheTpmbGV4O2dhcDo4cHg7anVzdGlmeS1jb250ZW50OmZsZXgtZW5kfQogIGF7Y29sb3I6dmFyKC0tYnJhbmQpO3RleHQtZGVjb3JhdGlvbjpub25lO2ZvbnQtd2VpZ2h0OjYwMH0KICAuZW1wdHl7dGV4dC1hbGlnbjpjZW50ZXI7Y29sb3I6dmFyKC0tbXV0ZWQpO3BhZGRpbmc6MzRweCAxNHB4fQogIC5lbXB0eSAuYmlne2ZvbnQtc2l6ZTozNHB4O21hcmdpbi1ib3R0b206OHB4fQogIC5oaW50e2JhY2tncm91bmQ6dmFyKC0tYnJhbmRmYWRlKTtib3JkZXI6MXB4IHNvbGlkIHZhcigtLWxpbmUpO2JvcmRlci1yYWRpdXM6MTJweDtwYWRkaW5nOjEwcHggMTJweDtmb250LXNpemU6MTIuNXB4O2NvbG9yOnZhcigtLW11dGVkKTttYXJnaW4tdG9wOjEwcHh9Cjwvc3R5bGU+CjwvaGVhZD4KPGJvZHk+CjxkaXYgaWQ9ImFwcCI+PC9kaXY+CjxkaXYgaWQ9InRvYXN0Ij48L2Rpdj4KCjxzY3JpcHQ+CmNvbnN0IEFQSSA9ICcnOwpsZXQgVE9LRU4gPSBsb2NhbFN0b3JhZ2UuZ2V0SXRlbSgncG1fdG9rZW4nKSB8fCBudWxsOwpsZXQgTUUgPSBudWxsOwpsZXQgVEFCID0gJ292ZXJ2aWV3JzsKY29uc3QgTUFSSyA9ICc8c3ZnIHdpZHRoPSIxNyIgaGVpZ2h0PSIxNyIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIj48cGF0aCBkPSJNMTIgMnYyME03IDVoN2EzLjUgMy41IDAgMDEwIDdIN20wIDBoOCIgc3Ryb2tlPSIjMDQyMzFiIiBzdHJva2Utd2lkdGg9IjIuMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIi8+PC9zdmc+JzsKCmFzeW5jIGZ1bmN0aW9uIGFwaShwYXRoLCBvcHRzPXt9KXsKICBjb25zdCBoZWFkZXJzID0gT2JqZWN0LmFzc2lnbih7J0NvbnRlbnQtVHlwZSc6J2FwcGxpY2F0aW9uL2pzb24nfSwgb3B0cy5oZWFkZXJzfHx7fSk7CiAgaWYgKFRPS0VOKSBoZWFkZXJzWydBdXRob3JpemF0aW9uJ10gPSAnQmVhcmVyICcgKyBUT0tFTjsKICBjb25zdCByZXMgPSBhd2FpdCBmZXRjaChBUEkgKyBwYXRoLCB7Li4ub3B0cywgaGVhZGVyc30pOwogIGxldCBkYXRhID0ge307IHRyeXsgZGF0YSA9IGF3YWl0IHJlcy5qc29uKCk7IH1jYXRjaHt9CiAgaWYoIXJlcy5vaykgdGhyb3cgbmV3IEVycm9yKGRhdGEuZXJyb3IgfHwgKCdIVFRQICcrcmVzLnN0YXR1cykpOwogIHJldHVybiBkYXRhOwp9CmZ1bmN0aW9uIHRvYXN0KG1zZywga2luZD0nJyl7CiAgY29uc3QgdD1kb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndG9hc3QnKTsKICB0LmlubmVySFRNTCA9ICc8ZGl2IGNsYXNzPSJ0b2FzdCAnK2tpbmQrJyI+Jytlc2MobXNnKSsnPC9kaXY+JzsKICBzZXRUaW1lb3V0KCgpPT57dC5pbm5lckhUTUw9Jyc7fSwgMzIwMCk7Cn0KZnVuY3Rpb24gZXNjKHMpe3JldHVybiBTdHJpbmcocz09bnVsbD8nJzpzKS5yZXBsYWNlKC9bJjw+Il0vZyxjPT4oeycmJzonJmFtcDsnLCc8JzonJmx0OycsJz4nOicmZ3Q7JywnIic6JyZxdW90Oyd9W2NdKSk7fQpmdW5jdGlvbiBtb25leShuKXtyZXR1cm4gJ1JzICcgKyBOdW1iZXIobnx8MCkudG9Mb2NhbGVTdHJpbmcoJ2VuLVBLJyk7fQpmdW5jdGlvbiB2YWwoaWQpe3JldHVybiBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChpZCkudmFsdWUudHJpbSgpO30KCi8vIC0tLS0tLS0tLS0gYXV0aCAtLS0tLS0tLS0tCmZ1bmN0aW9uIGxvZ2luVmlldygpewogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdhcHAnKS5pbm5lckhUTUwgPSBgCiAgPGRpdiBjbGFzcz0iY2VudGVyIj48ZGl2IGNsYXNzPSJjYXJkIGF1dGgiPgogICAgPGRpdiBjbGFzcz0iYnJhbmQiIHN0eWxlPSJmb250LXNpemU6MjZweDttYXJnaW4tYm90dG9tOjZweCI+PHNwYW4gY2xhc3M9Im1hcmsiIHN0eWxlPSJ3aWR0aDozOHB4O2hlaWdodDozOHB4Ij4ke01BUkt9PC9zcGFuPlBheTxzcGFuIHN0eWxlPSJjb2xvcjp2YXIoLS1icmFuZCkiPm1pbnQ8L3NwYW4+PC9kaXY+CiAgICA8ZGl2IGNsYXNzPSJtdXRlZCBzbWFsbCIgc3R5bGU9Im1hcmdpbi1ib3R0b206MThweCI+U2hvcGtlZXBlciAmIEFkbWluIGRhc2hib2FyZDwvZGl2PgogICAgPGRpdiBpZD0iYXV0aEZvcm1zIj48L2Rpdj4KICA8L2Rpdj48L2Rpdj5gOwogIHNob3dMb2dpbigpOwp9CmZ1bmN0aW9uIHNob3dMb2dpbigpewogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdhdXRoRm9ybXMnKS5pbm5lckhUTUwgPSBgCiAgICA8bGFiZWw+UGhvbmU8L2xhYmVsPjxpbnB1dCBpZD0ibF9waG9uZSIgcGxhY2Vob2xkZXI9IjAzeHh4eHh4eHh4IiBpbnB1dG1vZGU9Im51bWVyaWMiIC8+CiAgICA8bGFiZWw+UGFzc3dvcmQ8L2xhYmVsPjxpbnB1dCBpZD0ibF9wYXNzIiB0eXBlPSJwYXNzd29yZCIgLz4KICAgIDxidXR0b24gc3R5bGU9IndpZHRoOjEwMCU7bWFyZ2luLXRvcDoxNnB4O3BhZGRpbmc6MTNweCIgb25jbGljaz0iZG9Mb2dpbigpIj5Mb2dpbjwvYnV0dG9uPgogICAgPGRpdiBjbGFzcz0ic21hbGwgbXV0ZWQiIHN0eWxlPSJtYXJnaW4tdG9wOjE0cHg7dGV4dC1hbGlnbjpjZW50ZXIiPk5ldyBzaG9wa2VlcGVyPyA8YSBocmVmPSIjIiBvbmNsaWNrPSJzaG93UmVnKCk7cmV0dXJuIGZhbHNlIj5DcmVhdGUgYW4gYWNjb3VudDwvYT48L2Rpdj5gOwp9CmZ1bmN0aW9uIHNob3dSZWcoKXsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYXV0aEZvcm1zJykuaW5uZXJIVE1MID0gYAogICAgPGxhYmVsPllvdXIgbmFtZTwvbGFiZWw+PGlucHV0IGlkPSJyX25hbWUiIC8+CiAgICA8bGFiZWw+U2hvcCBuYW1lPC9sYWJlbD48aW5wdXQgaWQ9InJfc2hvcCIgLz4KICAgIDxsYWJlbD5QaG9uZTwvbGFiZWw+PGlucHV0IGlkPSJyX3Bob25lIiBwbGFjZWhvbGRlcj0iMDN4eHh4eHh4eHgiIGlucHV0bW9kZT0ibnVtZXJpYyIgLz4KICAgIDxsYWJlbD5QYXNzd29yZDwvbGFiZWw+PGlucHV0IGlkPSJyX3Bhc3MiIHR5cGU9InBhc3N3b3JkIiAvPgogICAgPGJ1dHRvbiBzdHlsZT0id2lkdGg6MTAwJTttYXJnaW4tdG9wOjE2cHg7cGFkZGluZzoxM3B4IiBvbmNsaWNrPSJkb1JlZygpIj5DcmVhdGUgYWNjb3VudDwvYnV0dG9uPgogICAgPGRpdiBjbGFzcz0iaGludCI+WW91ciBhY2NvdW50IHdpbGwgYWN0aXZhdGUgYWZ0ZXIgdGhlIGFkbWluIGFwcHJvdmVzIGl0LjwvZGl2PgogICAgPGRpdiBjbGFzcz0ic21hbGwgbXV0ZWQiIHN0eWxlPSJtYXJnaW4tdG9wOjEwcHg7dGV4dC1hbGlnbjpjZW50ZXIiPjxhIGhyZWY9IiMiIG9uY2xpY2s9InNob3dMb2dpbigpO3JldHVybiBmYWxzZSI+QmFjayB0byBsb2dpbjwvYT48L2Rpdj5gOwp9CmFzeW5jIGZ1bmN0aW9uIGRvTG9naW4oKXsKICB0cnl7CiAgICBjb25zdCBkID0gYXdhaXQgYXBpKCcvYXBpL2F1dGgvbG9naW4nLHttZXRob2Q6J1BPU1QnLGJvZHk6SlNPTi5zdHJpbmdpZnkoe3Bob25lOnZhbCgnbF9waG9uZScpLHBhc3N3b3JkOnZhbCgnbF9wYXNzJyl9KX0pOwogICAgVE9LRU49ZC50b2tlbjsgbG9jYWxTdG9yYWdlLnNldEl0ZW0oJ3BtX3Rva2VuJyxUT0tFTik7IE1FPWQudXNlcjsgVEFCPSdvdmVydmlldyc7IHNoZWxsKCk7CiAgfWNhdGNoKGUpeyB0b2FzdChlLm1lc3NhZ2UsJ2JhZCcpOyB9Cn0KYXN5bmMgZnVuY3Rpb24gZG9SZWcoKXsKICB0cnl7CiAgICBhd2FpdCBhcGkoJy9hcGkvYXV0aC9yZWdpc3Rlci1hZ2VudCcse21ldGhvZDonUE9TVCcsYm9keTpKU09OLnN0cmluZ2lmeSh7bmFtZTp2YWwoJ3JfbmFtZScpLHNob3BfbmFtZTp2YWwoJ3Jfc2hvcCcpLHBob25lOnZhbCgncl9waG9uZScpLHBhc3N3b3JkOnZhbCgncl9wYXNzJyl9KX0pOwogICAgdG9hc3QoJ0FjY291bnQgY3JlYXRlZCDigJQgd2FpdGluZyBmb3IgYWRtaW4gYXBwcm92YWwnLCdvaycpOyBzaG93TG9naW4oKTsKICB9Y2F0Y2goZSl7IHRvYXN0KGUubWVzc2FnZSwnYmFkJyk7IH0KfQpmdW5jdGlvbiBsb2dvdXQoKXtUT0tFTj1udWxsO01FPW51bGw7bG9jYWxTdG9yYWdlLnJlbW92ZUl0ZW0oJ3BtX3Rva2VuJyk7bG9naW5WaWV3KCk7fQoKLy8gLS0tLS0tLS0tLSBzaGVsbCAtLS0tLS0tLS0tCmZ1bmN0aW9uIHNoZWxsKCl7CiAgY29uc3QgaXNBZG1pbiA9IE1FLnJvbGU9PT0nYWRtaW4nOwogIGNvbnN0IHRhYnMgPSBpc0FkbWluCiAgICA/IFtbJ292ZXJ2aWV3JywnT3ZlcnZpZXcnXSxbJ2Vucm9sbG1lbnRzJywnQXBwcm92YWxzJ10sWydhZ2VudHMnLCdTaG9wa2VlcGVycyddLFsnY3VzdG9tZXJzJywnQ3VzdG9tZXJzJ10sWydyZW1pbmRlcnMnLCdSZW1pbmRlcnMnXV0KICAgIDogW1snb3ZlcnZpZXcnLCdPdmVydmlldyddLFsnbmV3Y3VzdG9tZXInLCdOZXcgc2FsZSddLFsnY3VzdG9tZXJzJywnTXkgY3VzdG9tZXJzJ10sWydyZW1pbmRlcnMnLCdSZW1pbmRlcnMnXV07CiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2FwcCcpLmlubmVySFRNTCA9IGAKICAgIDxoZWFkZXI+CiAgICAgIDxkaXYgY2xhc3M9ImJyYW5kIj48c3BhbiBjbGFzcz0ibWFyayI+JHtNQVJLfTwvc3Bhbj5QYXk8c3BhbiBzdHlsZT0iY29sb3I6dmFyKC0tYnJhbmQpIj5taW50PC9zcGFuPjwvZGl2PgogICAgICA8ZGl2IGNsYXNzPSJzcGFjZXIiPjwvZGl2PgogICAgICA8ZGl2IGNsYXNzPSJ3aG8iPjxiPiR7ZXNjKE1FLm5hbWUpfTwvYj4ke2lzQWRtaW4/J0FkbWluJzplc2MoTUUuc2hvcF9uYW1lfHwnU2hvcGtlZXBlcicpfTwvZGl2PgogICAgICA8YnV0dG9uIGNsYXNzPSJnaG9zdCBzbSIgb25jbGljaz0ibG9nb3V0KCkiPkxvZ291dDwvYnV0dG9uPgogICAgPC9oZWFkZXI+CiAgICA8ZGl2IGNsYXNzPSJ3cmFwIj4KICAgICAgPGRpdiBjbGFzcz0idGFicyI+JHt0YWJzLm1hcCgoW2ssbF0pPT5gPGJ1dHRvbiBjbGFzcz0iJHtUQUI9PT1rPydhY3RpdmUnOicnfSIgb25jbGljaz0iZ28oJyR7a30nKSI+JHtsfTwvYnV0dG9uPmApLmpvaW4oJycpfTwvZGl2PgogICAgICA8ZGl2IGlkPSJ2aWV3Ij48L2Rpdj4KICAgIDwvZGl2PmA7CiAgcmVuZGVyKCk7Cn0KZnVuY3Rpb24gZ28odCl7VEFCPXQ7c2hlbGwoKTt9Cgphc3luYyBmdW5jdGlvbiByZW5kZXIoKXsKICBjb25zdCB2PWRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCd2aWV3Jyk7CiAgdi5pbm5lckhUTUw9JzxkaXYgY2xhc3M9Im11dGVkIiBzdHlsZT0icGFkZGluZzoyMHB4Ij5Mb2FkaW5n4oCmPC9kaXY+JzsKICB0cnl7CiAgICBpZihUQUI9PT0nb3ZlcnZpZXcnKSByZXR1cm4gcmVuZGVyT3ZlcnZpZXcodik7CiAgICBpZihUQUI9PT0nZW5yb2xsbWVudHMnKSByZXR1cm4gcmVuZGVyRW5yb2xsbWVudHModik7CiAgICBpZihUQUI9PT0nYWdlbnRzJykgcmV0dXJuIHJlbmRlckFnZW50cyh2KTsKICAgIGlmKFRBQj09PSdjdXN0b21lcnMnKSByZXR1cm4gcmVuZGVyQ3VzdG9tZXJzKHYpOwogICAgaWYoVEFCPT09J3JlbWluZGVycycpIHJldHVybiByZW5kZXJSZW1pbmRlcnModik7CiAgICBpZihUQUI9PT0nbmV3Y3VzdG9tZXInKSByZXR1cm4gcmVuZGVyTmV3Q3VzdG9tZXIodik7CiAgfWNhdGNoKGUpeyB2LmlubmVySFRNTD0nPGRpdiBjbGFzcz0iY2FyZCIgc3R5bGU9ImJvcmRlci1jb2xvcjp2YXIoLS1yZWQpIj4nK2VzYyhlLm1lc3NhZ2UpKyc8L2Rpdj4nOyB9Cn0KCmZ1bmN0aW9uIGtwaShpYyxjb2xvcixsYWJlbCx2YWx1ZSl7CiAgcmV0dXJuIGA8ZGl2IGNsYXNzPSJrcGktY2FyZCI+PGRpdiBjbGFzcz0iaWMiIHN0eWxlPSJiYWNrZ3JvdW5kOiR7Y29sb3J9MjI7Y29sb3I6JHtjb2xvcn0iPiR7aWN9PC9kaXY+CiAgICA8ZGl2IGNsYXNzPSJsYmwiPiR7bGFiZWx9PC9kaXY+PGRpdiBjbGFzcz0idmFsIj4ke3ZhbHVlfTwvZGl2PjwvZGl2PmA7Cn0KYXN5bmMgZnVuY3Rpb24gcmVuZGVyT3ZlcnZpZXcodil7CiAgY29uc3Qge2N1c3RvbWVyc30gPSBhd2FpdCBhcGkoJy9hcGkvY3VzdG9tZXJzJyk7CiAgY29uc3QgYWN0aXZlID0gY3VzdG9tZXJzLmZpbHRlcihjPT5jLnN0YXR1cz09PSdhY3RpdmUnKTsKICBjb25zdCBwZW5kaW5nID0gY3VzdG9tZXJzLmZpbHRlcihjPT5jLnN0YXR1cz09PSdwZW5kaW5nJyk7CiAgY29uc3QgbG9ja2VkID0gYWN0aXZlLmZpbHRlcihjPT5jLmRldmljZV9sb2NrZWQpOwogIGNvbnN0IGZpbmFuY2VkID0gYWN0aXZlLnJlZHVjZSgocyxjKT0+cytjLnN1bW1hcnkudG90YWxfZmluYW5jZWQsMCk7CiAgY29uc3QgY29sbGVjdGVkID0gYWN0aXZlLnJlZHVjZSgocyxjKT0+cytjLnN1bW1hcnkucGFpZCwwKTsKICBjb25zdCBvdXRzdGFuZGluZyA9IGFjdGl2ZS5yZWR1Y2UoKHMsYyk9PnMrYy5zdW1tYXJ5LnJlbWFpbmluZywwKTsKICBjb25zdCBwY3QgPSBmaW5hbmNlZD8gTWF0aC5yb3VuZChjb2xsZWN0ZWQvZmluYW5jZWQqMTAwKTowOwogIHYuaW5uZXJIVE1MID0gYAogICAgPGRpdiBjbGFzcz0iY2FyZCI+CiAgICAgIDxkaXYgY2xhc3M9ImJldHdlZW4iPjxkaXY+PGRpdiBjbGFzcz0ibXV0ZWQgc21hbGwiPlRvdGFsIGNvbGxlY3RlZDwvZGl2PgogICAgICAgIDxkaXYgc3R5bGU9ImZvbnQtc2l6ZTozMHB4O2ZvbnQtd2VpZ2h0OjgwMDtsZXR0ZXItc3BhY2luZzotLjZweCI+JHttb25leShjb2xsZWN0ZWQpfTwvZGl2PjwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9InBpbGwgYWN0aXZlIj4ke3BjdH0lIG9mICR7bW9uZXkoZmluYW5jZWQpfTwvZGl2PjwvZGl2PgogICAgICA8ZGl2IGNsYXNzPSJiYXIiPjxpIHN0eWxlPSJ3aWR0aDoke3BjdH0lIj48L2k+PC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9Im11dGVkIHNtYWxsIj5PdXRzdGFuZGluZzogPGIgc3R5bGU9ImNvbG9yOnZhcigtLXRleHQpIj4ke21vbmV5KG91dHN0YW5kaW5nKX08L2I+PC9kaXY+CiAgICA8L2Rpdj4KICAgIDxkaXYgY2xhc3M9ImdyaWQiPgogICAgICAke2twaSgn8J+RpScsJ3ZhcigtLWJyYW5kKScsJ0FjdGl2ZSBjdXN0b21lcnMnLGFjdGl2ZS5sZW5ndGgpfQogICAgICAke2twaSgn4o+zJywndmFyKC0tYW1iZXIpJywnUGVuZGluZyBhcHByb3ZhbCcscGVuZGluZy5sZW5ndGgpfQogICAgICAke2twaSgn8J+UkicsJ3ZhcigtLXJlZCknLCdMb2NrZWQgZGV2aWNlcycsbG9ja2VkLmxlbmd0aCl9CiAgICAgICR7a3BpKCfwn5OmJywndmFyKC0tYmx1ZSknLCdGaW5hbmNlZCcsbW9uZXkoZmluYW5jZWQpKX0KICAgIDwvZGl2PmA7Cn0KCmFzeW5jIGZ1bmN0aW9uIHJlbmRlckFnZW50cyh2KXsKICBjb25zdCB7YWdlbnRzfSA9IGF3YWl0IGFwaSgnL2FwaS9hZG1pbi9hZ2VudHMnKTsKICBpZighYWdlbnRzLmxlbmd0aCl7IHYuaW5uZXJIVE1MPWVtcHR5U3RhdGUoJ/Cfj6onLCdObyBzaG9wa2VlcGVycyB5ZXQnLCdTaG9wa2VlcGVycyByZWdpc3RlciB0aGVtc2VsdmVzLCB0aGVuIHlvdSBhcHByb3ZlIHRoZW0gaGVyZS4nKTsgcmV0dXJuOyB9CiAgdi5pbm5lckhUTUwgPSBhZ2VudHMubWFwKGE9PmA8ZGl2IGNsYXNzPSJjYXJkIj48ZGl2IGNsYXNzPSJiZXR3ZWVuIj4KICAgICAgPGRpdj48Yj4ke2VzYyhhLm5hbWUpfTwvYj4gPHNwYW4gY2xhc3M9InBpbGwgJHthLnN0YXR1c30iPiR7YS5zdGF0dXN9PC9zcGFuPgogICAgICAgIDxkaXYgY2xhc3M9Im11dGVkIHNtYWxsIiBzdHlsZT0ibWFyZ2luLXRvcDozcHgiPiR7ZXNjKGEuc2hvcF9uYW1lfHwn4oCUJyl9IMK3ICR7ZXNjKGEucGhvbmUpfTwvZGl2PjwvZGl2PgogICAgICA8ZGl2IGNsYXNzPSJyb3ciPgogICAgICAgICR7YS5zdGF0dXMhPT0nYWN0aXZlJz9gPGJ1dHRvbiBjbGFzcz0ib2sgc20iIG9uY2xpY2s9ImFnZW50QWN0aW9uKCR7YS5pZH0sJ2FwcHJvdmUnKSI+QXBwcm92ZTwvYnV0dG9uPmA6Jyd9CiAgICAgICAgJHthLnN0YXR1cz09PSdhY3RpdmUnP2A8YnV0dG9uIGNsYXNzPSJiYWQgc20iIG9uY2xpY2s9ImFnZW50QWN0aW9uKCR7YS5pZH0sJ3N1c3BlbmQnKSI+U3VzcGVuZDwvYnV0dG9uPmA6Jyd9CiAgICAgIDwvZGl2PjwvZGl2PjwvZGl2PmApLmpvaW4oJycpOwp9CmFzeW5jIGZ1bmN0aW9uIGFnZW50QWN0aW9uKGlkLGFjdCl7IHRyeXsgYXdhaXQgYXBpKGAvYXBpL2FkbWluL2FnZW50cy8ke2lkfS8ke2FjdH1gLHttZXRob2Q6J1BPU1QnfSk7IHRvYXN0KCdEb25lJywnb2snKTsgcmVuZGVyKCk7IH1jYXRjaChlKXt0b2FzdChlLm1lc3NhZ2UsJ2JhZCcpO30gfQoKYXN5bmMgZnVuY3Rpb24gcmVuZGVyRW5yb2xsbWVudHModil7CiAgY29uc3Qge2Vucm9sbG1lbnRzfSA9IGF3YWl0IGFwaSgnL2FwaS9hZG1pbi9lbnJvbGxtZW50cz9zdGF0dXM9cGVuZGluZycpOwogIGlmKCFlbnJvbGxtZW50cy5sZW5ndGgpeyB2LmlubmVySFRNTD1lbXB0eVN0YXRlKCfinIUnLCdBbGwgY2xlYXInLCdObyBlbnJvbGxtZW50cyB3YWl0aW5nIGZvciBhcHByb3ZhbC4nKTsgcmV0dXJuOyB9CiAgdi5pbm5lckhUTUwgPSBlbnJvbGxtZW50cy5tYXAoYz0+YAogICAgPGRpdiBjbGFzcz0iY2FyZCI+CiAgICAgIDxkaXYgY2xhc3M9ImJldHdlZW4iPjxkaXY+PGI+JHtlc2MoYy5uYW1lKX08L2I+IDxzcGFuIGNsYXNzPSJwaWxsIHBlbmRpbmciPnBlbmRpbmc8L3NwYW4+PC9kaXY+CiAgICAgICAgPHNwYW4gY2xhc3M9Im11dGVkIHNtYWxsIj4ke2VzYyhjLmFnZW50X25hbWUpfSDCtyAke2VzYyhjLmFnZW50X3Nob3B8fCfigJQnKX08L3NwYW4+PC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9InNtYWxsIG11dGVkIiBzdHlsZT0ibWFyZ2luOjdweCAwIj4ke2VzYyhjLnBob25lKX0gwrcgQ05JQyAke2VzYyhjLmNuaWN8fCfigJQnKX0gwrcgJHtlc2MoYy5wcm9kdWN0fHwn4oCUJyl9PC9kaXY+CiAgICAgIDxkaXYgY2xhc3M9InNtYWxsIj5QcmljZSAke21vbmV5KGMudG90YWxfcHJpY2UpfSDCtyBEb3duICR7bW9uZXkoYy5kb3duX3BheW1lbnQpfSDCtyAke2MubW9udGhzfSBtb250aHM8L2Rpdj4KICAgICAgPGRpdiBjbGFzcz0idGh1bWJzIiBzdHlsZT0ibWFyZ2luOjEycHggMCI+CiAgICAgICAgJHtjLnNlbGZpZV91cmw/YDxpbWcgc3JjPSIke2Muc2VsZmllX3VybH0iIG9uY2xpY2s9Im9wZW5JbWcoJyR7Yy5zZWxmaWVfdXJsfScpIiB0aXRsZT0iU2VsZmllIj5gOicnfQogICAgICAgICR7Yy5jbmljX3VybD9gPGltZyBzcmM9IiR7Yy5jbmljX3VybH0iIG9uY2xpY2s9Im9wZW5JbWcoJyR7Yy5jbmljX3VybH0nKSIgdGl0bGU9IkNOSUMiPmA6Jyd9CiAgICAgIDwvZGl2PgogICAgICA8ZGl2IGNsYXNzPSJyb3ciPgogICAgICAgIDxidXR0b24gY2xhc3M9Im9rIiBvbmNsaWNrPSJhcHByb3ZlQ3VzdCgke2MuaWR9KSI+QXBwcm92ZSAmIGVucm9sbDwvYnV0dG9uPgogICAgICAgIDxidXR0b24gY2xhc3M9ImJhZCIgb25jbGljaz0icmVqZWN0Q3VzdCgke2MuaWR9KSI+UmVqZWN0PC9idXR0b24+CiAgICAgIDwvZGl2PgogICAgPC9kaXY+YCkuam9pbignJyk7Cn0KYXN5bmMgZnVuY3Rpb24gYXBwcm92ZUN1c3QoaWQpeyB0cnl7IGF3YWl0IGFwaShgL2FwaS9hZG1pbi9jdXN0b21lcnMvJHtpZH0vYXBwcm92ZWAse21ldGhvZDonUE9TVCd9KTsgdG9hc3QoJ0Vucm9sbGVkIOKAlCBpbnN0YWxsbWVudCBwbGFuIGNyZWF0ZWQnLCdvaycpOyByZW5kZXIoKTsgfWNhdGNoKGUpe3RvYXN0KGUubWVzc2FnZSwnYmFkJyk7fSB9CmFzeW5jIGZ1bmN0aW9uIHJlamVjdEN1c3QoaWQpeyBjb25zdCByZWFzb249cHJvbXB0KCdSZWFzb24gZm9yIHJlamVjdGlvbj8nKXx8Jyc7IHRyeXsgYXdhaXQgYXBpKGAvYXBpL2FkbWluL2N1c3RvbWVycy8ke2lkfS9yZWplY3RgLHttZXRob2Q6J1BPU1QnLGJvZHk6SlNPTi5zdHJpbmdpZnkoe3JlYXNvbn0pfSk7IHRvYXN0KCdSZWplY3RlZCcsJ29rJyk7IHJlbmRlcigpOyB9Y2F0Y2goZSl7dG9hc3QoZS5tZXNzYWdlLCdiYWQnKTt9IH0KCmFzeW5jIGZ1bmN0aW9uIHJlbmRlckN1c3RvbWVycyh2KXsKICBjb25zdCB7Y3VzdG9tZXJzfSA9IGF3YWl0IGFwaSgnL2FwaS9jdXN0b21lcnMnKTsKICBpZighY3VzdG9tZXJzLmxlbmd0aCl7IHYuaW5uZXJIVE1MPWVtcHR5U3RhdGUoJ/Cfp74nLCdObyBjdXN0b21lcnMgeWV0JywgTUUucm9sZT09PSdhZG1pbic/J0FwcHJvdmVkIHNhbGVzIGFwcGVhciBoZXJlLic6J1RhcCDigJxOZXcgc2FsZeKAnSB0byBhZGQgeW91ciBmaXJzdCBjdXN0b21lci4nKTsgcmV0dXJuOyB9CiAgdi5pbm5lckhUTUwgPSBjdXN0b21lcnMubWFwKGM9PnsKICAgIGNvbnN0IHM9Yy5zdW1tYXJ5OwogICAgY29uc3QgcGN0ID0gcy50b3RhbF9maW5hbmNlZD8gTWF0aC5yb3VuZChzLnBhaWQvcy50b3RhbF9maW5hbmNlZCoxMDApOjA7CiAgICBjb25zdCBhY3RpdmUgPSBjLnN0YXR1cz09PSdhY3RpdmUnfHxjLnN0YXR1cz09PSdjb21wbGV0ZWQnOwogICAgcmV0dXJuIGA8ZGl2IGNsYXNzPSJjYXJkIj4KICAgICAgPGRpdiBjbGFzcz0iYmV0d2VlbiI+CiAgICAgICAgPGRpdj48Yj4ke2VzYyhjLm5hbWUpfTwvYj4gPHNwYW4gY2xhc3M9InBpbGwgJHtjLnN0YXR1c30iPiR7Yy5zdGF0dXN9PC9zcGFuPgogICAgICAgICAgJHtjLmRldmljZV9sb2NrZWQ/JzxzcGFuIGNsYXNzPSJwaWxsIGxvY2tlZCI+8J+UkiBsb2NrZWQ8L3NwYW4+JzonJ308L2Rpdj4KICAgICAgICAke2FjdGl2ZT9gPHNwYW4gY2xhc3M9Im11dGVkIHNtYWxsIj4ke3BjdH0lPC9zcGFuPmA6Jyd9CiAgICAgIDwvZGl2PgogICAgICA8ZGl2IGNsYXNzPSJtdXRlZCBzbWFsbCIgc3R5bGU9Im1hcmdpbjo0cHggMCAycHgiPiR7ZXNjKGMucGhvbmUpfSDCtyAke2VzYyhjLnByb2R1Y3R8fCfigJQnKX08L2Rpdj4KICAgICAgJHthY3RpdmU/YAogICAgICAgIDxkaXYgY2xhc3M9ImJhciI+PGkgc3R5bGU9IndpZHRoOiR7cGN0fSUiPjwvaT48L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJiZXR3ZWVuIHNtYWxsIj4KICAgICAgICAgIDxzcGFuPlBhaWQgPGI+JHttb25leShzLnBhaWQpfTwvYj4gLyAke21vbmV5KHMudG90YWxfZmluYW5jZWQpfTwvc3Bhbj4KICAgICAgICAgICR7cy5vdmVyZHVlP2A8c3BhbiBzdHlsZT0iY29sb3I6dmFyKC0tcmVkKSI+4pqgICR7cy5vdmVyZHVlfSBvdmVyZHVlPC9zcGFuPmA6KHMubmV4dF9kdWU/YDxzcGFuIGNsYXNzPSJtdXRlZCI+TmV4dCAke3MubmV4dF9kdWUuZHVlX2RhdGV9PC9zcGFuPmA6JycpfQogICAgICAgIDwvZGl2PgogICAgICAgIDxidXR0b24gY2xhc3M9Imdob3N0IHNtIiBzdHlsZT0ibWFyZ2luLXRvcDoxMXB4IiBvbmNsaWNrPSJvcGVuQ3VzdCgke2MuaWR9KSI+VmlldyBpbnN0YWxsbWVudHM8L2J1dHRvbj4KICAgICAgYDooYy5zdGF0dXM9PT0ncmVqZWN0ZWQnP2A8ZGl2IGNsYXNzPSJzbWFsbCIgc3R5bGU9ImNvbG9yOnZhcigtLXJlZCkiPlJlamVjdGVkOiAke2VzYyhjLnJlamVjdF9yZWFzb258fCfigJQnKX08L2Rpdj5gOmA8ZGl2IGNsYXNzPSJzbWFsbCBtdXRlZCI+4o+zIEF3YWl0aW5nIGFkbWluIGFwcHJvdmFsPC9kaXY+YCl9CiAgICA8L2Rpdj5gOwogIH0pLmpvaW4oJycpOwp9CmFzeW5jIGZ1bmN0aW9uIG9wZW5DdXN0KGlkKXsKICBjb25zdCB7Y3VzdG9tZXI6Y30gPSBhd2FpdCBhcGkoJy9hcGkvY3VzdG9tZXJzLycraWQpOwogIGNvbnN0IHRkID0gbmV3IERhdGUoKS50b0lTT1N0cmluZygpLnNsaWNlKDAsMTApOwogIGNvbnN0IHJvd3MgPSBjLmluc3RhbGxtZW50cy5tYXAoaT0+YDx0cj4KICAgIDx0ZD4ke2kuc2VxfTwvdGQ+PHRkPiR7bW9uZXkoaS5hbW91bnQpfTwvdGQ+PHRkPiR7aS5kdWVfZGF0ZX08L3RkPgogICAgPHRkPiR7aS5wYWlkP2A8c3BhbiBjbGFzcz0icGlsbCBwYWlkIj5wYWlkPC9zcGFuPmA6KGkuZHVlX2RhdGU8dGQ/YDxzcGFuIGNsYXNzPSJwaWxsIG92ZXJkdWUiPm92ZXJkdWU8L3NwYW4+YDpgPHNwYW4gY2xhc3M9InBpbGwgcGVuZGluZyI+ZHVlPC9zcGFuPmApfTwvdGQ+CiAgICA8dGQ+JHtpLnBhaWQ/ZXNjKGkubWV0aG9kfHwnJyk6YDxidXR0b24gY2xhc3M9InNtIiBvbmNsaWNrPSJwYXlJbnN0KCR7aS5pZH0sJHtpZH0pIj5QYXk8L2J1dHRvbj5gfTwvdGQ+CiAgPC90cj5gKS5qb2luKCcnKTsKICBjb25zdCBwY3Q9Yy5zdW1tYXJ5LnRvdGFsX2ZpbmFuY2VkP01hdGgucm91bmQoYy5zdW1tYXJ5LnBhaWQvYy5zdW1tYXJ5LnRvdGFsX2ZpbmFuY2VkKjEwMCk6MDsKICBkbGcoYCR7ZXNjKGMubmFtZSl9YCwgYAogICAgPGRpdiBjbGFzcz0iYmFyIj48aSBzdHlsZT0id2lkdGg6JHtwY3R9JSI+PC9pPjwvZGl2PgogICAgPGRpdiBjbGFzcz0iYmV0d2VlbiBzbWFsbCIgc3R5bGU9Im1hcmdpbi1ib3R0b206MTJweCI+CiAgICAgIDxzcGFuPlBhaWQgPGI+JHttb25leShjLnN1bW1hcnkucGFpZCl9PC9iPjwvc3Bhbj4KICAgICAgPHNwYW4+UmVtYWluaW5nIDxiPiR7bW9uZXkoYy5zdW1tYXJ5LnJlbWFpbmluZyl9PC9iPjwvc3Bhbj4KICAgICAgJHtjLmRldmljZV9sb2NrZWQ/JzxzcGFuIGNsYXNzPSJwaWxsIGxvY2tlZCI+8J+UkiBsb2NrZWQ8L3NwYW4+JzonJ30KICAgIDwvZGl2PgogICAgPHRhYmxlPjx0cj48dGg+IzwvdGg+PHRoPkFtb3VudDwvdGg+PHRoPkR1ZTwvdGg+PHRoPlN0YXR1czwvdGg+PHRoPjwvdGg+PC90cj4ke3Jvd3N9PC90YWJsZT5gLAogICAgYDxidXR0b24gY2xhc3M9Imdob3N0IiBvbmNsaWNrPSJjbG9zZURsZygpIj5DbG9zZTwvYnV0dG9uPmApOwp9CmFzeW5jIGZ1bmN0aW9uIHBheUluc3QoaW5zdElkLGN1c3RJZCl7CiAgY29uc3QgbWV0aG9kID0gcHJvbXB0KCdQYXltZW50IG1ldGhvZD8gKGphenpjYXNoIC8gZWFzeXBhaXNhIC8gY2FzaCknLCdjYXNoJyl8fCdjYXNoJzsKICBjb25zdCB0eG4gPSBtZXRob2Q9PT0nY2FzaCc/Jyc6KHByb21wdCgnVHJhbnNhY3Rpb24gcmVmZXJlbmNlPycpfHwnJyk7CiAgdHJ5eyBhd2FpdCBhcGkoYC9hcGkvaW5zdGFsbG1lbnRzLyR7aW5zdElkfS9wYXlgLHttZXRob2Q6J1BPU1QnLGJvZHk6SlNPTi5zdHJpbmdpZnkoe21ldGhvZCx0eG5fcmVmOnR4bn0pfSk7IHRvYXN0KCdQYXltZW50IHJlY29yZGVkJywnb2snKTsgY2xvc2VEbGcoKTsgb3BlbkN1c3QoY3VzdElkKTsgfWNhdGNoKGUpe3RvYXN0KGUubWVzc2FnZSwnYmFkJyk7fQp9Cgphc3luYyBmdW5jdGlvbiByZW5kZXJSZW1pbmRlcnModil7CiAgY29uc3Qge3JlbWluZGVycyx0aHJvdWdofSA9IGF3YWl0IGFwaSgnL2FwaS9yZW1pbmRlcnMnKTsKICBpZighcmVtaW5kZXJzLmxlbmd0aCl7IHYuaW5uZXJIVE1MPWVtcHR5U3RhdGUoJ/CflJQnLCdOb3RoaW5nIGR1ZScsJ05vIGluc3RhbGxtZW50cyBkdWUgaW4gdGhlIG5leHQgMiBkYXlzLicpOyByZXR1cm47IH0KICB2LmlubmVySFRNTCA9IGA8ZGl2IGNsYXNzPSJjYXJkIj4KICAgIDxkaXYgY2xhc3M9Im11dGVkIHNtYWxsIiBzdHlsZT0ibWFyZ2luLWJvdHRvbToxMHB4Ij5EdWUgb24gb3IgYmVmb3JlIDxiIHN0eWxlPSJjb2xvcjp2YXIoLS10ZXh0KSI+JHt0aHJvdWdofTwvYj48L2Rpdj4KICAgIDx0YWJsZT48dHI+PHRoPkN1c3RvbWVyPC90aD48dGg+UGhvbmU8L3RoPjx0aD4jPC90aD48dGg+QW1vdW50PC90aD48dGg+RHVlPC90aD48L3RyPgogICAgJHtyZW1pbmRlcnMubWFwKHI9PmA8dHI+PHRkPiR7ZXNjKHIuY3VzdG9tZXJfbmFtZSl9PC90ZD48dGQ+JHtlc2Moci5jdXN0b21lcl9waG9uZSl9PC90ZD48dGQ+JHtyLnNlcX08L3RkPjx0ZD4ke21vbmV5KHIuYW1vdW50KX08L3RkPjx0ZD4ke3IuZHVlX2RhdGV9PC90ZD48L3RyPmApLmpvaW4oJycpfQogICAgPC90YWJsZT48L2Rpdj5gOwp9CgpmdW5jdGlvbiByZW5kZXJOZXdDdXN0b21lcih2KXsKICB2LmlubmVySFRNTCA9IGA8ZGl2IGNsYXNzPSJjYXJkIj4KICAgIDxoMyBzdHlsZT0ibWFyZ2luOjAgMCA0cHgiPk5ldyBpbnN0YWxsbWVudCBzYWxlPC9oMz4KICAgIDxkaXYgY2xhc3M9Im11dGVkIHNtYWxsIiBzdHlsZT0ibWFyZ2luLWJvdHRvbTo2cHgiPkN1c3RvbWVyIGRldGFpbHMgKyBwaG90b3MuIEFkbWluIHdpbGwgcmV2aWV3IGJlZm9yZSBlbnJvbGxtZW50LjwvZGl2PgogICAgPGxhYmVsPkN1c3RvbWVyIG5hbWU8L2xhYmVsPjxpbnB1dCBpZD0ibl9uYW1lIiAvPgogICAgPGxhYmVsPlBob25lPC9sYWJlbD48aW5wdXQgaWQ9Im5fcGhvbmUiIHBsYWNlaG9sZGVyPSIwM3h4eHh4eHh4eCIgaW5wdXRtb2RlPSJudW1lcmljIiAvPgogICAgPGxhYmVsPkNOSUMgbnVtYmVyPC9sYWJlbD48aW5wdXQgaWQ9Im5fY25pYyIgcGxhY2Vob2xkZXI9Inh4eHh4LXh4eHh4eHgteCIgLz4KICAgIDxsYWJlbD5Qcm9kdWN0IChlLmcuIHBob25lIG1vZGVsKTwvbGFiZWw+PGlucHV0IGlkPSJuX3Byb2R1Y3QiIC8+CiAgICA8ZGl2IGNsYXNzPSJncmlkIiBzdHlsZT0iZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOjFmciAxZnIgMWZyO2dhcDoxMHB4Ij4KICAgICAgPGRpdj48bGFiZWw+VG90YWwgcHJpY2U8L2xhYmVsPjxpbnB1dCBpZD0ibl90b3RhbCIgdHlwZT0ibnVtYmVyIiBpbnB1dG1vZGU9Im51bWVyaWMiIC8+PC9kaXY+CiAgICAgIDxkaXY+PGxhYmVsPkRvd24gcGF5bWVudDwvbGFiZWw+PGlucHV0IGlkPSJuX2Rvd24iIHR5cGU9Im51bWJlciIgaW5wdXRtb2RlPSJudW1lcmljIiAvPjwvZGl2PgogICAgICA8ZGl2PjxsYWJlbD5Nb250aHM8L2xhYmVsPjxpbnB1dCBpZD0ibl9tb250aHMiIHR5cGU9Im51bWJlciIgaW5wdXRtb2RlPSJudW1lcmljIiAvPjwvZGl2PgogICAgPC9kaXY+CiAgICA8bGFiZWw+Q3VzdG9tZXIgc2VsZmllIChyZXF1aXJlZCk8L2xhYmVsPjxpbnB1dCBpZD0ibl9zZWxmaWUiIHR5cGU9ImZpbGUiIGFjY2VwdD0iaW1hZ2UvKiIgY2FwdHVyZT0idXNlciIgLz4KICAgIDxsYWJlbD5DTklDIHBob3RvIChyZXF1aXJlZCk8L2xhYmVsPjxpbnB1dCBpZD0ibl9jbmljaW1nIiB0eXBlPSJmaWxlIiBhY2NlcHQ9ImltYWdlLyoiIGNhcHR1cmU9ImVudmlyb25tZW50IiAvPgogICAgPGRpdiBjbGFzcz0iaGludCI+Q3VzdG9tZXIgY29uc2VudHMgdG8gdGhlIGluc3RhbGxtZW50IHRlcm1zIOKAlCBpbmNsdWRpbmcgdGhhdCB0aGUgZGV2aWNlIG1heSBiZSBsb2NrZWQgZm9yIG1pc3NlZCBwYXltZW50cyDigJQgYmVmb3JlIGVucm9sbG1lbnQuPC9kaXY+CiAgICA8YnV0dG9uIHN0eWxlPSJtYXJnaW4tdG9wOjE0cHg7d2lkdGg6MTAwJTtwYWRkaW5nOjEzcHgiIGlkPSJuX3N1Ym1pdCIgb25jbGljaz0ic3VibWl0Q3VzdG9tZXIoKSI+U3VibWl0IGZvciBhcHByb3ZhbDwvYnV0dG9uPgogIDwvZGl2PmA7Cn0KZnVuY3Rpb24gZmlsZVRvRGF0YVVybChpbnB1dCl7CiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlKT0+ewogICAgY29uc3QgZj1pbnB1dC5maWxlcyYmaW5wdXQuZmlsZXNbMF07IGlmKCFmKSByZXR1cm4gcmVzb2x2ZShudWxsKTsKICAgIGNvbnN0IHI9bmV3IEZpbGVSZWFkZXIoKTsgci5vbmxvYWQ9KCk9PnJlc29sdmUoci5yZXN1bHQpOyByLnJlYWRBc0RhdGFVUkwoZik7CiAgfSk7Cn0KYXN5bmMgZnVuY3Rpb24gc3VibWl0Q3VzdG9tZXIoKXsKICBjb25zdCBidG49ZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ25fc3VibWl0Jyk7IGJ0bi5kaXNhYmxlZD10cnVlOyBidG4udGV4dENvbnRlbnQ9J1N1Ym1pdHRpbmfigKYnOwogIHRyeXsKICAgIGNvbnN0IHNlbGZpZT1hd2FpdCBmaWxlVG9EYXRhVXJsKGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCduX3NlbGZpZScpKTsKICAgIGNvbnN0IGNuaWNfcGhvdG89YXdhaXQgZmlsZVRvRGF0YVVybChkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbl9jbmljaW1nJykpOwogICAgaWYoIXNlbGZpZXx8IWNuaWNfcGhvdG8peyB0b2FzdCgnU2VsZmllIGFuZCBDTklDIHBob3RvIGFyZSByZXF1aXJlZCcsJ2JhZCcpOyBidG4uZGlzYWJsZWQ9ZmFsc2U7IGJ0bi50ZXh0Q29udGVudD0nU3VibWl0IGZvciBhcHByb3ZhbCc7IHJldHVybjsgfQogICAgYXdhaXQgYXBpKCcvYXBpL2N1c3RvbWVycycse21ldGhvZDonUE9TVCcsYm9keTpKU09OLnN0cmluZ2lmeSh7CiAgICAgIG5hbWU6dmFsKCduX25hbWUnKSxwaG9uZTp2YWwoJ25fcGhvbmUnKSxjbmljOnZhbCgnbl9jbmljJykscHJvZHVjdDp2YWwoJ25fcHJvZHVjdCcpLAogICAgICB0b3RhbF9wcmljZTp2YWwoJ25fdG90YWwnKSxkb3duX3BheW1lbnQ6dmFsKCduX2Rvd24nKSxtb250aHM6dmFsKCduX21vbnRocycpLCBzZWxmaWUsIGNuaWNfcGhvdG8KICAgIH0pfSk7CiAgICB0b2FzdCgnU3VibWl0dGVkIGZvciBhZG1pbiBhcHByb3ZhbCcsJ29rJyk7IGdvKCdjdXN0b21lcnMnKTsKICB9Y2F0Y2goZSl7IHRvYXN0KGUubWVzc2FnZSwnYmFkJyk7IGJ0bi5kaXNhYmxlZD1mYWxzZTsgYnRuLnRleHRDb250ZW50PSdTdWJtaXQgZm9yIGFwcHJvdmFsJzsgfQp9CgpmdW5jdGlvbiBlbXB0eVN0YXRlKGljLHRpdGxlLHN1Yil7IHJldHVybiBgPGRpdiBjbGFzcz0iY2FyZCI+PGRpdiBjbGFzcz0iZW1wdHkiPjxkaXYgY2xhc3M9ImJpZyI+JHtpY308L2Rpdj48Yj4ke2VzYyh0aXRsZSl9PC9iPjxkaXYgY2xhc3M9InNtYWxsIiBzdHlsZT0ibWFyZ2luLXRvcDo0cHgiPiR7ZXNjKHN1Yil9PC9kaXY+PC9kaXY+PC9kaXY+YDsgfQoKZnVuY3Rpb24gZGxnKHRpdGxlLGJvZHksZm9vdGVyKXsKICBsZXQgZD1kb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZGxnJyk7IGlmKGQpIGQucmVtb3ZlKCk7CiAgZD1kb2N1bWVudC5jcmVhdGVFbGVtZW50KCdkaWFsb2cnKTsgZC5pZD0nZGxnJzsKICBkLmlubmVySFRNTD1gPGRpdiBjbGFzcz0iZGxnLWgiPiR7dGl0bGV9PC9kaXY+PGRpdiBjbGFzcz0iZGxnLWIiPiR7Ym9keX08L2Rpdj48ZGl2IGNsYXNzPSJkbGctZiI+JHtmb290ZXJ8fCcnfTwvZGl2PmA7CiAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChkKTsgZC5zaG93TW9kYWwoKTsKfQpmdW5jdGlvbiBjbG9zZURsZygpe2NvbnN0IGQ9ZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2RsZycpOyBpZihkKXtkLmNsb3NlKCk7ZC5yZW1vdmUoKTt9fQpmdW5jdGlvbiBvcGVuSW1nKHVybCl7IGRsZygnUGhvdG8nLGA8aW1nIHNyYz0iJHt1cmx9IiBzdHlsZT0id2lkdGg6MTAwJTtib3JkZXItcmFkaXVzOjEycHgiPmAsYDxidXR0b24gY2xhc3M9Imdob3N0IiBvbmNsaWNrPSJjbG9zZURsZygpIj5DbG9zZTwvYnV0dG9uPmApOyB9CgooYXN5bmMgZnVuY3Rpb24oKXsKICBpZihUT0tFTil7CiAgICB0cnl7IGNvbnN0IGQ9YXdhaXQgYXBpKCcvYXBpL21lJyk7IE1FPWQudXNlcjsgc2hlbGwoKTsgcmV0dXJuOyB9Y2F0Y2h7IGxvZ291dCgpOyB9CiAgfQogIGxvZ2luVmlldygpOwp9KSgpOwo8L3NjcmlwdD4KPC9ib2R5Pgo8L2h0bWw+Cg==', 'base64').toString('utf8');

// ---------- auth ----------
'use strict';
// Zero-dependency auth: scrypt password hashing + HMAC-signed tokens (JWT-like).

const SECRET = process.env.APP_SECRET || 'dev-secret-change-me';

function hashPassword(password) {
  const salt = crypto.randomBytes(16);
  const hash = crypto.scryptSync(String(password), salt, 32);
  return `scrypt$${salt.toString('hex')}$${hash.toString('hex')}`;
}

function verifyPassword(password, stored) {
  try {
    const [, saltHex, hashHex] = stored.split('$');
    const salt = Buffer.from(saltHex, 'hex');
    const expected = Buffer.from(hashHex, 'hex');
    const actual = crypto.scryptSync(String(password), salt, 32);
    return crypto.timingSafeEqual(actual, expected);
  } catch {
    return false;
  }
}

function b64url(buf) {
  return Buffer.from(buf).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
function b64urlJson(obj) {
  return b64url(JSON.stringify(obj));
}
function fromB64url(str) {
  return Buffer.from(str.replace(/-/g, '+').replace(/_/g, '/'), 'base64');
}

// Minimal JWT (HS256).
function signToken(payload, expiresInSec = 60 * 60 * 24 * 7) {
  const header = { alg: 'HS256', typ: 'JWT' };
  const body = { ...payload, iat: Math.floor(Date.now() / 1000), exp: Math.floor(Date.now() / 1000) + expiresInSec };
  const data = `${b64urlJson(header)}.${b64urlJson(body)}`;
  const sig = b64url(crypto.createHmac('sha256', SECRET).update(data).digest());
  return `${data}.${sig}`;
}

function verifyToken(token) {
  try {
    const [h, p, s] = String(token).split('.');
    if (!h || !p || !s) return null;
    const data = `${h}.${p}`;
    const expected = b64url(crypto.createHmac('sha256', SECRET).update(data).digest());
    const a = Buffer.from(s);
    const b = Buffer.from(expected);
    if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return null;
    const payload = JSON.parse(fromB64url(p).toString('utf8'));
    if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) return null;
    return payload;
  } catch {
    return null;
  }
}



// ---------- db ----------
'use strict';
// Zero-dependency SQLite layer using Node's built-in node:sqlite (Node 22+).

const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, '..', 'data');
fs.mkdirSync(DATA_DIR, { recursive: true });
const DB_PATH = process.env.DB_PATH || path.join(DATA_DIR, 'paymint.db');

const db = new DatabaseSync(DB_PATH);
db.exec('PRAGMA journal_mode = WAL;');
db.exec('PRAGMA foreign_keys = ON;');

db.exec(`
CREATE TABLE IF NOT EXISTS users (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  role         TEXT NOT NULL CHECK(role IN ('admin','agent')),
  name         TEXT NOT NULL,
  shop_name    TEXT,
  phone        TEXT UNIQUE NOT NULL,
  password     TEXT NOT NULL,           -- scrypt hash
  status       TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','active','suspended')),
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS customers (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  agent_id     INTEGER NOT NULL REFERENCES users(id),
  name         TEXT NOT NULL,
  phone        TEXT NOT NULL,
  cnic         TEXT,                     -- CNIC number
  selfie_path  TEXT,                     -- stored image file
  cnic_path    TEXT,                     -- stored image file
  product      TEXT,                     -- what was sold (e.g. phone model)
  total_price  REAL NOT NULL DEFAULT 0,
  down_payment REAL NOT NULL DEFAULT 0,
  months       INTEGER NOT NULL DEFAULT 0,
  status       TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','active','rejected','completed')),
  reject_reason TEXT,
  device_locked INTEGER NOT NULL DEFAULT 0,  -- 0/1, controlled after missed payment
  device_id    TEXT,                     -- registered lock-app device identifier
  created_at   TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS installments (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  customer_id  INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  seq          INTEGER NOT NULL,         -- 1..months
  amount       REAL NOT NULL,
  due_date     TEXT NOT NULL,            -- YYYY-MM-DD
  paid         INTEGER NOT NULL DEFAULT 0,
  paid_at      TEXT,
  method       TEXT,                     -- jazzcash / easypaisa / cash
  txn_ref      TEXT
);

CREATE INDEX IF NOT EXISTS idx_customers_agent ON customers(agent_id);
CREATE INDEX IF NOT EXISTS idx_inst_customer ON installments(customer_id);
CREATE INDEX IF NOT EXISTS idx_inst_due ON installments(due_date, paid);
`);



// ---------- seed admin on startup (idempotent) ----------
(function(){
  const existing = db.prepare("SELECT id FROM users WHERE role='admin'").get();
  if(!existing){
    const phone = process.env.ADMIN_PHONE || '03000000000';
    const pass = process.env.ADMIN_PASSWORD || 'admin123';
    const name = process.env.ADMIN_NAME || 'Owner';
    db.prepare("INSERT INTO users (role,name,phone,password,status) VALUES ('admin',?,?,?, 'active')").run(name, phone, hashPassword(pass));
    console.log('Admin seeded: phone=' + phone);
  }
})();

// ---------- server ----------
'use strict';
// Zero-dependency HTTP server for Paymint backend + dashboard.

const PORT = process.env.PORT || 3000;
const UPLOAD_DIR = process.env.UPLOAD_DIR || path.join(DATA_DIR, 'uploads');
fs.mkdirSync(UPLOAD_DIR, { recursive: true });

// ---------- tiny helpers ----------
function send(res, status, body, headers = {}) {
  const payload = typeof body === 'string' || Buffer.isBuffer(body) ? body : JSON.stringify(body);
  res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', ...headers });
  res.end(payload);
}
function readBody(req, limit = 12 * 1024 * 1024) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let size = 0;
    req.on('data', (c) => {
      size += c.length;
      if (size > limit) { reject(new Error('payload too large')); req.destroy(); return; }
      chunks.push(c);
    });
    req.on('end', () => {
      const raw = Buffer.concat(chunks).toString('utf8');
      if (!raw) return resolve({});
      try { resolve(JSON.parse(raw)); } catch { reject(new Error('invalid JSON')); }
    });
    req.on('error', reject);
  });
}
function today() { return new Date().toISOString().slice(0, 10); }
function addMonths(dateStr, n) {
  const d = new Date(dateStr + 'T00:00:00Z');
  d.setUTCMonth(d.getUTCMonth() + n);
  return d.toISOString().slice(0, 10);
}
function saveImage(dataUrl, prefix) {
  if (!dataUrl || typeof dataUrl !== 'string') return null;
  const m = dataUrl.match(/^data:(image\/(png|jpe?g|webp));base64,(.+)$/);
  if (!m) return null;
  const ext = m[2] === 'jpeg' ? 'jpg' : m[2];
  const name = `${prefix}_${Date.now()}_${crypto.randomBytes(4).toString('hex')}.${ext}`;
  fs.writeFileSync(path.join(UPLOAD_DIR, name), Buffer.from(m[3], 'base64'));
  return name;
}

// ---------- auth middleware ----------
function authUser(req) {
  const h = req.headers['authorization'] || '';
  const token = h.startsWith('Bearer ') ? h.slice(7) : null;
  if (!token) return null;
  const payload = verifyToken(token);
  if (!payload) return null;
  const user = db.prepare('SELECT id, role, name, shop_name, phone, status FROM users WHERE id = ?').get(payload.uid);
  if (!user || user.status !== 'active') return null;
  return user;
}

// ---------- domain logic ----------
function generateSchedule(customer) {
  const principal = Math.max(0, customer.total_price - customer.down_payment);
  const months = customer.months;
  if (months <= 0) return;
  const base = Math.floor((principal / months) * 100) / 100;
  let allocated = 0;
  const stmt = db.prepare('INSERT INTO installments (customer_id, seq, amount, due_date) VALUES (?,?,?,?)');
  for (let i = 1; i <= months; i++) {
    let amt = base;
    if (i === months) amt = Math.round((principal - allocated) * 100) / 100; // last catches rounding
    allocated += base;
    stmt.run(customer.id, i, amt, addMonths(today(), i));
  }
}

// A customer SHOULD be locked if any installment is overdue and unpaid.
function overdueCount(customerId) {
  return db.prepare(
    "SELECT COUNT(*) c FROM installments WHERE customer_id = ? AND paid = 0 AND due_date < ?"
  ).get(customerId, today()).c;
}
function refreshLockState(customerId) {
  const c = db.prepare('SELECT status FROM customers WHERE id = ?').get(customerId);
  if (!c) return;
  const locked = c.status === 'active' && overdueCount(customerId) > 0 ? 1 : 0;
  db.prepare('UPDATE customers SET device_locked = ? WHERE id = ?').run(locked, customerId);
}

function customerView(c) {
  const inst = db.prepare('SELECT * FROM installments WHERE customer_id = ? ORDER BY seq').all(c.id);
  const paid = inst.filter(i => i.paid).reduce((s, i) => s + i.amount, 0);
  const total = inst.reduce((s, i) => s + i.amount, 0);
  const nextDue = inst.find(i => !i.paid) || null;
  return {
    ...c,
    selfie_url: c.selfie_path ? `/api/files/${c.selfie_path}` : null,
    cnic_url: c.cnic_path ? `/api/files/${c.cnic_path}` : null,
    installments: inst,
    summary: {
      total_financed: Math.round(total * 100) / 100,
      paid: Math.round(paid * 100) / 100,
      remaining: Math.round((total - paid) * 100) / 100,
      overdue: overdueCount(c.id),
      next_due: nextDue ? { seq: nextDue.seq, amount: nextDue.amount, due_date: nextDue.due_date } : null,
    },
  };
}

// ---------- routes ----------
const routes = [];
function route(method, pattern, handler) {
  const keys = [];
  const rx = new RegExp('^' + pattern.replace(/:[^/]+/g, (m) => { keys.push(m.slice(1)); return '([^/]+)'; }) + '$');
  routes.push({ method, rx, keys, handler });
}

// --- Auth ---
route('POST', '/api/auth/register-agent', async (req, res) => {
  const b = await readBody(req);
  if (!b.name || !b.phone || !b.password) return send(res, 400, { error: 'name, phone, password required' });
  const exists = db.prepare('SELECT id FROM users WHERE phone = ?').get(b.phone);
  if (exists) return send(res, 409, { error: 'phone already registered' });
  const info = db.prepare(
    "INSERT INTO users (role, name, shop_name, phone, password, status) VALUES ('agent',?,?,?,?,'pending')"
  ).run(b.name, b.shop_name || null, b.phone, hashPassword(b.password));
  send(res, 201, { id: info.lastInsertRowid, status: 'pending', message: 'Account created. Waiting for admin approval.' });
});

route('POST', '/api/auth/login', async (req, res) => {
  const b = await readBody(req);
  const u = db.prepare('SELECT * FROM users WHERE phone = ?').get(b.phone || '');
  if (!u || !verifyPassword(b.password || '', u.password)) return send(res, 401, { error: 'invalid phone or password' });
  if (u.status === 'pending') return send(res, 403, { error: 'account pending admin approval' });
  if (u.status === 'suspended') return send(res, 403, { error: 'account suspended' });
  const token = signToken({ uid: u.id, role: u.role });
  send(res, 200, { token, user: { id: u.id, role: u.role, name: u.name, shop_name: u.shop_name, phone: u.phone } });
});

route('GET', '/api/me', async (req, res, _p, user) => {
  if (!user) return send(res, 401, { error: 'unauthorized' });
  send(res, 200, { user });
});

// --- Admin: agents ---
route('GET', '/api/admin/agents', async (req, res, _p, user) => {
  if (!user || user.role !== 'admin') return send(res, 403, { error: 'admin only' });
  const rows = db.prepare("SELECT id, name, shop_name, phone, status, created_at FROM users WHERE role='agent' ORDER BY created_at DESC").all();
  send(res, 200, { agents: rows });
});
route('POST', '/api/admin/agents/:id/approve', async (req, res, p, user) => {
  if (!user || user.role !== 'admin') return send(res, 403, { error: 'admin only' });
  db.prepare("UPDATE users SET status='active' WHERE id=? AND role='agent'").run(p.id);
  send(res, 200, { ok: true });
});
route('POST', '/api/admin/agents/:id/suspend', async (req, res, p, user) => {
  if (!user || user.role !== 'admin') return send(res, 403, { error: 'admin only' });
  db.prepare("UPDATE users SET status='suspended' WHERE id=? AND role='agent'").run(p.id);
  send(res, 200, { ok: true });
});

// --- Admin: enrollment approvals ---
route('GET', '/api/admin/enrollments', async (req, res, _p, user) => {
  if (!user || user.role !== 'admin') return send(res, 403, { error: 'admin only' });
  const status = new URL(req.url, 'http://x').searchParams.get('status') || 'pending';
  const rows = db.prepare(`
    SELECT c.*, u.name agent_name, u.shop_name agent_shop
    FROM customers c JOIN users u ON u.id = c.agent_id
    WHERE c.status = ? ORDER BY c.created_at DESC`).all(status);
  send(res, 200, { enrollments: rows.map(customerView) });
});
route('POST', '/api/admin/customers/:id/approve', async (req, res, p, user) => {
  if (!user || user.role !== 'admin') return send(res, 403, { error: 'admin only' });
  const c = db.prepare('SELECT * FROM customers WHERE id = ?').get(p.id);
  if (!c) return send(res, 404, { error: 'not found' });
  if (c.status !== 'pending') return send(res, 400, { error: 'already processed' });
  db.prepare("UPDATE customers SET status='active' WHERE id=?").run(c.id);
  const fresh = db.prepare('SELECT * FROM customers WHERE id = ?').get(c.id);
  generateSchedule(fresh);
  refreshLockState(c.id);
  send(res, 200, { ok: true });
});
route('POST', '/api/admin/customers/:id/reject', async (req, res, p, user) => {
  if (!user || user.role !== 'admin') return send(res, 403, { error: 'admin only' });
  const b = await readBody(req);
  db.prepare("UPDATE customers SET status='rejected', reject_reason=? WHERE id=? AND status='pending'").run(b.reason || null, p.id);
  send(res, 200, { ok: true });
});

// --- Agent: customers ---
route('POST', '/api/customers', async (req, res, _p, user) => {
  if (!user || user.role !== 'agent') return send(res, 403, { error: 'agent only' });
  const b = await readBody(req);
  if (!b.name || !b.phone) return send(res, 400, { error: 'name and phone required' });
  if (!b.selfie || !b.cnic_photo) return send(res, 400, { error: 'customer selfie and CNIC photo required for enrollment' });
  const selfie_path = saveImage(b.selfie, 'selfie');
  const cnic_path = saveImage(b.cnic_photo, 'cnic');
  if (!selfie_path || !cnic_path) return send(res, 400, { error: 'images must be base64 data URLs (png/jpg/webp)' });
  const info = db.prepare(`
    INSERT INTO customers (agent_id, name, phone, cnic, selfie_path, cnic_path, product, total_price, down_payment, months, status)
    VALUES (?,?,?,?,?,?,?,?,?,?, 'pending')`).run(
    user.id, b.name, b.phone, b.cnic || null, selfie_path, cnic_path, b.product || null,
    Number(b.total_price) || 0, Number(b.down_payment) || 0, Number(b.months) || 0);
  send(res, 201, { id: info.lastInsertRowid, status: 'pending', message: 'Enrollment submitted for admin approval.' });
});
route('GET', '/api/customers', async (req, res, _p, user) => {
  if (!user) return send(res, 401, { error: 'unauthorized' });
  const rows = user.role === 'admin'
    ? db.prepare('SELECT * FROM customers ORDER BY created_at DESC').all()
    : db.prepare('SELECT * FROM customers WHERE agent_id = ? ORDER BY created_at DESC').all(user.id);
  send(res, 200, { customers: rows.map(customerView) });
});
route('GET', '/api/customers/:id', async (req, res, p, user) => {
  if (!user) return send(res, 401, { error: 'unauthorized' });
  const c = db.prepare('SELECT * FROM customers WHERE id = ?').get(p.id);
  if (!c) return send(res, 404, { error: 'not found' });
  if (user.role === 'agent' && c.agent_id !== user.id) return send(res, 403, { error: 'forbidden' });
  refreshLockState(c.id);
  send(res, 200, { customer: customerView(db.prepare('SELECT * FROM customers WHERE id = ?').get(c.id)) });
});

// --- Payments / installments ---
route('POST', '/api/installments/:id/pay', async (req, res, p, user) => {
  if (!user) return send(res, 401, { error: 'unauthorized' });
  const b = await readBody(req);
  const inst = db.prepare('SELECT * FROM installments WHERE id = ?').get(p.id);
  if (!inst) return send(res, 404, { error: 'not found' });
  const c = db.prepare('SELECT * FROM customers WHERE id = ?').get(inst.customer_id);
  if (user.role === 'agent' && c.agent_id !== user.id) return send(res, 403, { error: 'forbidden' });
  if (inst.paid) return send(res, 400, { error: 'already paid' });
  db.prepare("UPDATE installments SET paid=1, paid_at=datetime('now'), method=?, txn_ref=? WHERE id=?")
    .run(b.method || 'cash', b.txn_ref || null, inst.id);
  // complete customer if all paid
  const remaining = db.prepare('SELECT COUNT(*) c FROM installments WHERE customer_id=? AND paid=0').get(inst.customer_id).c;
  if (remaining === 0) db.prepare("UPDATE customers SET status='completed', device_locked=0 WHERE id=?").run(inst.customer_id);
  else refreshLockState(inst.customer_id);
  send(res, 200, { ok: true, remaining });
});

// --- Reminders: installments due within 2 days, unpaid ---
route('GET', '/api/reminders', async (req, res, _p, user) => {
  if (!user) return send(res, 401, { error: 'unauthorized' });
  const t = today();
  const in2 = addMonths; // not used; compute 2 days
  const d = new Date(t + 'T00:00:00Z'); d.setUTCDate(d.getUTCDate() + 2);
  const limit = d.toISOString().slice(0, 10);
  const base = `
    SELECT i.id, i.seq, i.amount, i.due_date, c.id customer_id, c.name customer_name, c.phone customer_phone, c.agent_id
    FROM installments i JOIN customers c ON c.id = i.customer_id
    WHERE i.paid = 0 AND c.status = 'active' AND i.due_date <= ?`;
  const rows = user.role === 'admin'
    ? db.prepare(base + ' ORDER BY i.due_date').all(limit)
    : db.prepare(base + ' AND c.agent_id = ? ORDER BY i.due_date').all(limit, user.id);
  send(res, 200, { reminders: rows, as_of: t, through: limit });
});

// --- Device lock polling (used by the lock APK) ---
route('POST', '/api/device/register', async (req, res, _p, user) => {
  if (!user) return send(res, 401, { error: 'unauthorized' });
  const b = await readBody(req);
  const c = db.prepare('SELECT * FROM customers WHERE id = ?').get(b.customer_id);
  if (!c) return send(res, 404, { error: 'customer not found' });
  if (user.role === 'agent' && c.agent_id !== user.id) return send(res, 403, { error: 'forbidden' });
  db.prepare('UPDATE customers SET device_id = ? WHERE id = ?').run(b.device_id || null, c.id);
  send(res, 200, { ok: true });
});
// Lock app polls this (device_id acts as shared identifier). Returns whether device should be locked.
route('GET', '/api/device/status', async (req, res) => {
  const device_id = new URL(req.url, 'http://x').searchParams.get('device_id');
  if (!device_id) return send(res, 400, { error: 'device_id required' });
  const c = db.prepare('SELECT * FROM customers WHERE device_id = ?').get(device_id);
  if (!c) return send(res, 404, { error: 'device not registered' });
  refreshLockState(c.id);
  const fresh = db.prepare('SELECT device_locked, status FROM customers WHERE id = ?').get(c.id);
  send(res, 200, {
    locked: !!fresh.device_locked,
    status: fresh.status,
    message: fresh.device_locked
      ? 'Aapki installment due hai. Bara-e-karam ada karein taake phone unlock ho jaye.'
      : 'OK',
  });
});

// ---------- static + files ----------
const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png', '.jpg': 'image/jpeg', '.webp': 'image/webp', '.svg': 'image/svg+xml' };
function serveStatic(res, filePath) {
  fs.readFile(filePath, (err, data) => {
    if (err) return send(res, 404, { error: 'not found' });
    res.writeHead(200, { 'Content-Type': MIME[path.extname(filePath)] || 'application/octet-stream' });
    res.end(data);
  });
}

const server = http.createServer(async (req, res) => {
  try {
    const url = new URL(req.url, 'http://x');
    const pathname = decodeURIComponent(url.pathname);

    // uploaded files (auth-gated)
    if (pathname.startsWith('/api/files/')) {
      const user = authUser(req);
      if (!user) return send(res, 401, { error: 'unauthorized' });
      const name = path.basename(pathname.slice('/api/files/'.length));
      return serveStatic(res, path.join(UPLOAD_DIR, name));
    }

    if (pathname.startsWith('/api/')) {
      const match = routes.find(r => r.method === req.method && r.rx.test(pathname));
      if (!match) return send(res, 404, { error: 'route not found' });
      const m = pathname.match(match.rx);
      const params = {};
      match.keys.forEach((k, i) => { params[k] = m[i + 1]; });
      const needsAuth = !['/api/auth/login', '/api/auth/register-agent', '/api/device/status'].includes(pathname);
      const user = authUser(req);
      if (needsAuth && !user) return send(res, 401, { error: 'unauthorized' });
      return match.handler(req, res, params, user);
    }

          // static dashboard (embedded)
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      return res.end(EMBEDDED_HTML);
  } catch (e) {
    send(res, e.message === 'invalid JSON' || e.message === 'payload too large' ? 400 : 500, { error: e.message });
  }
});

server.listen(PORT, () => console.log(`Paymint backend running on http://localhost:${PORT}`));

